### ISSUE TITLE
haproxy: unable to view stats when a server is in error

### ISSUE THREAD

**Issue by lgrawet** [Aidaho12/haproxy-wi#254]
Hi,

Is is possible to disable the big red "popup" in the haproxy stats page ? I have some servers in error (for good reasons) and I can't scroll the page anymore to view meaningful information for most of backends/frontends.

Thanks

Laurent

**Comment by lgrawet** [comment]
Or maybe a new option ?

**Comment by Aidaho12** [comment]
Hi

Sorry, it's unclear for me... Do you mean that there are a lot of a red servers on the stat page?

**Comment by lgrawet** [comment]
In my version, if you have only one red server, the page is rendered with a red background and no more way to scroll over it. I have to monitor other backends/frontends which are not rendered on this part of the page.

**Comment by Aidaho12** [comment]
Oh, I see, which version do you use? There was this bag

**Comment by lgrawet** [comment]
I've updated to the latest release, same problem.

```
# git log -1
commit d5a8cd5ba9cba267420cf1d15874506a0f98e519
Author: Pavel Loginov <buffoon2001@mail.ru>
Date:   Sun Nov 29 12:45:28 2020 +0600

    v4.5.4.0
    
    Changelog: https://haproxy-wi.org/changelog.py#4_5_4
```

**Comment by Aidaho12** [comment]
Try to clear cache вторник, 01 декабря 2020г., 14:32 +06:00 от Laurent Grawet  notifications@github.com :

**Comment by lgrawet** [comment]
I already tried that.
Also tried another browser (chrome instead of firefox)

**Comment by Aidaho12** [comment]
It's strange... Have files updated in inc folder?

**Comment by Aidaho12** [comment]
Hm... It's strange. Have files updated in inc folder? вторник, 01 декабря 2020г., 15:02 +06:00 от Laurent Grawet  notifications@github.com :

**Comment by lgrawet** [comment]
Yes they are all up to date.
The strange thing is that I have the problem with an haproxy server but not another.

**Comment by lgrawet** [comment]
![status_display_problem](https://user-images.githubusercontent.com/10059091/101131332-66101b00-3605-11eb-8ff5-26d78ca90180.png)

**Comment by Aidaho12** [comment]
This problem definitely was, and it's definitely has been fixed. You can see it on demo site

**Comment by lgrawet** [comment]
I started over from a fresh clone and I still have the problem.
I had to bypass the toastr.error() function as a workaround

```
function showStats() {
        $.ajax( {
                url: "options.py",
                data: {
                        act: "stats",
                        serv: $("#serv").val(),
                        service: $("#service").val(),
                        token: $('#token').val()
                },
                type: "POST",
                success: function( data ) {
                        //if (data.indexOf('error:') != '-1' && data.indexOf('Internal error:') == '-1') {
                        if (false) {
                                toastr.error(data);
                        } else {
                                toastr.clear();
                                $("#ajax").html(data);
                                window.history.pushState("Stats", "Stats", cur_url[0] + "?service=" + $("#service").val() + "&serv=" +
 $("#serv").val());
                                wait();
                        }
                }
        } );
```

**Comment by Aidaho12** [comment]
Ok, bug was in this function пятница, 04 декабря 2020г., 13:43 +06:00 от Laurent Grawet  notifications@github.com :

**Comment by lgrawet** [comment]
How can I help you to debug this ?

**Comment by lgrawet** [comment]
Hi,
Any update on this ?
I still have the problem with latest version:

```
commit 3c8ab621fd768cf33f78cca486f921220d57025a
Author: Pavel Loginov <buffoon2001@mail.ru>
Date:   Mon Jan 18 22:21:51 2021 +0600

    v4.5.8.0
```

**Comment by Aidaho12** [comment]
Hi

No, I can't reproduce it

**Comment by lgrawet** [comment]
Is there any information I can provide to help you on this (sql query..) ?

**Comment by Aidaho12** [comment]
MB output from ajax request and script.js

**Comment by lgrawet** [comment]
Hi,

I've just found out the problem using mozilla debugger.  This is due to "Socket error: Connection reset by peer" in data variable. I use a script + xinetd on DB servers to identify the primary. The check returns an http status but haproxy gets "Socket error: Connection reset by peer" at the end. This is not a problem when haproxy gets the right http status for primary, but I get the socket error in status page for secondary. I have to improve the script but this is another story.

This is just to show your why the toast.error function is a very bad idea in it's current implementation. I was unable to scroll the page up/down to the error. I had to use the mozilla debugger...
The error is already visible with a red background in the original page, there is no need for an unscrollable popup.

Kind regards,

Laurent
